services:
    mongo:
        image: mongo:6.0
        container_name: mongo_db
        ports:
            - '27017:27017'
        volumes:
            - ./mongo-data:/data/db
    mongo-express:
        image: mongo-express:1.0.0-alpha.4
        container_name: mongo-express
        depends_on:
            - mongo
        ports:
            - '8081:8081'
        environment:
            ME_CONFIG_MONGODB_SERVER: mongo
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_ADMINUSERNAME: ''
            ME_CONFIG_MONGODB_ADMINPASSWORD: ''
            ME_CONFIG_SITE_BASEURL: '/'
            ME_CONFIG_BASICAUTH_USERNAME: admin
            ME_CONFIG_BASICAUTH_PASSWORD: secret

